//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDoc
    {
        public int id { get; set; }
        public string clientId { get; set; }
        public string doctorId { get; set; }
        public Nullable<int> diseaseId { get; set; }
        public string documentName { get; set; }
        public string path { get; set; }
    
        public virtual ClientDetail Client { get; set; }
        public virtual ClientDoc ClientDoc1 { get; set; }
        public virtual ClientDoc ClientDoc2 { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
